# Generated by Django 6.0.3 on 2026-04-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reverse_name', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#6c757d', max_length=20)),
            ],
            options={
                'verbose_name': 'Тип связи',
                'verbose_name_plural': 'Типы связей',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('strength', models.IntegerField(choices=[(1, 'Weak'), (2, 'Medium'), (3, 'Strong')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='elements.element')),
                ('to_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='elements.element')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.relationshiptype')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
                'unique_together': {('from_element', 'to_element', 'relationship_type')},
            },
        ),
    ]
