# Generated by Django 6.0.3 on 2026-04-07 14:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_alter_elementtype_options_element_created_by_and_more'),
        ('relationships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'ordering': ['name'], 'verbose_name': 'Тип связи', 'verbose_name_plural': 'Типы связей'},
        ),
        migrations.AddField(
            model_name='relationship',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительные атрибуты'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='icon',
            field=models.CharField(default='link', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='is_bidirectional',
            field=models.BooleanField(default=False, verbose_name='Двунаправленная'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание связи'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='from_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='elements.element', verbose_name='От элемента'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='relationships.relationshiptype', verbose_name='Тип связи'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='strength',
            field=models.IntegerField(choices=[(1, 'Очень слабая'), (2, 'Слабая'), (3, 'Средняя'), (4, 'Сильная'), (5, 'Очень сильная')], default=3, verbose_name='Сила связи'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='to_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='elements.element', verbose_name='К элементу'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='color',
            field=models.CharField(default='#6c757d', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название связи'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='reverse_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Обратное название'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['from_element', 'to_element'], name='relationshi_from_el_b5a5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['relationship_type'], name='relationshi_relatio_cf780a_idx'),
        ),
    ]
