# Generated by Django 6.0.3 on 2026-04-07 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_element_fields_schema_alter_element_data_and_more'),
        ('relationships', '0002_alter_relationshiptype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='relationship',
            name='relationshi_relatio_cf780a_idx',
        ),
        migrations.RemoveField(
            model_name='relationshiptype',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='from_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='elements.element'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='relationships.relationshiptype'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='strength',
            field=models.IntegerField(choices=[(1, 'Очень слабая'), (2, 'Слабая'), (3, 'Средняя'), (4, 'Сильная'), (5, 'Очень сильная')], default=3),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='to_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='elements.element'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='color',
            field=models.CharField(default='#6C5CE7', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='updated_at',
        ),
    ]
