# Generated by Django 6.0.3 on 2026-04-11 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_elementtype_color_elementtype_updated_at'),
        ('relationships', '0003_remove_relationship_relationshi_relatio_cf780a_idx_and_more'),
        ('worlds', '0003_remove_worldinvitation_invited_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['-created_at'], 'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'ordering': ['-is_system', 'name'], 'verbose_name': 'Тип связи', 'verbose_name_plural': 'Типы связей'},
        ),
        migrations.AddField(
            model_name='relationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Системный тип'),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_types', to='worlds.world'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='strength',
            field=models.IntegerField(choices=[(1, 'Очень слабая'), (2, 'Слабая'), (3, 'Средняя'), (4, 'Сильная'), (5, 'Очень сильная')], default=3, verbose_name='Сила связи'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='color',
            field=models.CharField(default='#8b5cf6', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='is_bidirectional',
            field=models.BooleanField(default=True, verbose_name='Двунаправленная'),
        ),
        migrations.AlterUniqueTogether(
            name='relationshiptype',
            unique_together={('world', 'name')},
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['from_element', 'relationship_type'], name='relationshi_from_el_c89b08_idx'),
        ),
    ]
