# Generated by Django 6.0.3 on 2026-04-07 14:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('galleries', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='content_type',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alt текст'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='file_size',
            field=models.IntegerField(default=0, verbose_name='Размер файла (байты)'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип файла'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery_images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название галереи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('object_id', models.PositiveIntegerField()),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичная галерея')),
                ('max_images', models.IntegerField(default=50, verbose_name='Максимум изображений')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_galleries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='galleries.gallery', verbose_name='Галерея'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['gallery', 'order'], name='galleries_g_gallery_dad88e_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['is_primary'], name='galleries_g_is_prim_29f5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['content_type', 'object_id'], name='galleries_g_content_0cdd8d_idx'),
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
    ]
