# Generated by Django 6.0.3 on 2026-04-07 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Просмотр'), ('editor', 'Редактор'), ('admin', 'Администратор')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
        migrations.AddField(
            model_name='world',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='world_covers/%Y/%m/%d/', verbose_name='Обложка мира'),
        ),
        migrations.AddField(
            model_name='world',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='world',
            name='theme_color',
            field=models.CharField(default='#667eea', max_length=20, verbose_name='Цвет темы'),
        ),
        migrations.AlterField(
            model_name='world',
            name='description',
            field=models.TextField(help_text='Опишите ваш мир', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(help_text='Придумайте название для вашего мира', max_length=200, verbose_name='Название мира'),
        ),
        migrations.AddIndex(
            model_name='world',
            index=models.Index(fields=['creator', '-created_at'], name='worlds_worl_creator_4d5a8a_idx'),
        ),
        migrations.AddField(
            model_name='worldinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worldinvitation',
            name='invited_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='world_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worldinvitation',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='worlds.world'),
        ),
    ]
