# Generated by Django 6.0.3 on 2026-04-07 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_worldinvitation_world_cover_image_world_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldinvitation',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='worldinvitation',
            name='invited_user',
        ),
        migrations.RemoveField(
            model_name='worldinvitation',
            name='world',
        ),
        migrations.RemoveIndex(
            model_name='world',
            name='worlds_worl_creator_4d5a8a_idx',
        ),
        migrations.AlterField(
            model_name='world',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='world',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название мира'),
        ),
        migrations.AlterField(
            model_name='world',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='WorldInvitation',
        ),
        migrations.RemoveField(
            model_name='world',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='world',
            name='theme_color',
        ),
    ]
