# Generated by Django 6.0.3 on 2026-04-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название элемента')),
                ('data', models.JSONField(default=dict, verbose_name='Данные элемента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('fields_schema', models.JSONField(default=dict, verbose_name='Схема полей')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#007bff', max_length=20, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип элемента',
                'verbose_name_plural': 'Типы элементов',
            },
        ),
    ]
