# Generated by Django 6.0.3 on 2026-04-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='worlds.world'),
        ),
        migrations.AddField(
            model_name='elementtype',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_types', to='worlds.world', verbose_name='Мир'),
        ),
        migrations.AddField(
            model_name='element',
            name='element_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='elements.elementtype'),
        ),
        migrations.AlterUniqueTogether(
            name='elementtype',
            unique_together={('name', 'world')},
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['world', 'element_type'], name='elements_el_world_i_8d9a38_idx'),
        ),
    ]
