# Generated by Django 6.0.3 on 2026-04-07 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_initial'),
        ('worlds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elementtype',
            options={'ordering': ['name'], 'verbose_name': 'Тип элемента', 'verbose_name_plural': 'Типы элементов'},
        ),
        migrations.AddField(
            model_name='element',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_elements', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='elementtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание типа'),
        ),
        migrations.AddField(
            model_name='elementtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='elements.elementtype', verbose_name='Тип элемента'),
        ),
        migrations.AlterField(
            model_name='element',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='worlds.world', verbose_name='Мир'),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['name'], name='elements_el_name_a94bab_idx'),
        ),
    ]
