# Generated by Django 6.0.3 on 2026-04-07 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_alter_elementtype_options_element_created_by_and_more'),
        ('worlds', '0003_remove_worldinvitation_invited_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Название поля')),
                ('field_type', models.CharField(choices=[('text', 'Текстовое поле'), ('textarea', 'Большое текстовое поле'), ('number', 'Число'), ('boolean', 'Да/Нет'), ('date', 'Дата'), ('datetime', 'Дата и время'), ('color', 'Цвет'), ('image', 'Изображение'), ('url', 'Ссылка')], default='text', max_length=50)),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Поле элемента',
                'verbose_name_plural': 'Поля элементов',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['-created_at'], 'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
        migrations.AlterModelOptions(
            name='elementtype',
            options={'verbose_name': 'Категория элемента', 'verbose_name_plural': 'Категории элементов'},
        ),
        migrations.RemoveIndex(
            model_name='element',
            name='elements_el_world_i_8d9a38_idx',
        ),
        migrations.RemoveIndex(
            model_name='element',
            name='elements_el_name_a94bab_idx',
        ),
        migrations.RemoveField(
            model_name='elementtype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='elementtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='elementtype',
            name='fields_schema',
        ),
        migrations.RemoveField(
            model_name='elementtype',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='element',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='elements.elementtype'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='element',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='worlds.world'),
        ),
        migrations.AlterField(
            model_name='elementtype',
            name='icon',
            field=models.CharField(default='cube', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='elementtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='elementtype',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_types', to='worlds.world'),
        ),
        migrations.AddField(
            model_name='elementfield',
            name='element_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='elements.elementtype'),
        ),
        migrations.RemoveField(
            model_name='element',
            name='created_by',
        ),
    ]
