# Generated by Django 6.0.3 on 2026-04-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_elementfield_alter_element_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='fields_schema',
            field=models.JSONField(default=dict, verbose_name='Схема полей'),
        ),
        migrations.AlterField(
            model_name='element',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Данные элемента'),
        ),
        migrations.DeleteModel(
            name='ElementField',
        ),
    ]
