# Generated by Django 6.0.3 on 2026-04-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_element_fields_schema_alter_element_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementtype',
            name='color',
            field=models.CharField(blank=True, default='#6d28d9', max_length=7),
        ),
        migrations.AddField(
            model_name='elementtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
